version: "3.8"

services:
  redisjobs_to_chtables:
    build: .
    container_name: "redisjobs_to_chtables"
    env_file: ./.env
    stop_grace_period: 3m # See README.md. Equivalent to `docker stop -t 180`
    command: ["node", "/app/build/src/main.js"]
